name: Deploy on README Change

on:
  push:
    paths:
      - 'README.md'
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
    - name: Deploy to GitHub
      run: |
        git add .
        git commit -m "Auto-deploy: Update README" || exit 0
        git push